---
baseurl: "https://robbhagle.com/"
languageCode: "en-us"
title: "Robb Hagle"
metaDataFormat: "yaml"
params:

  # Website information
  title: "Robb Hagle"
  subtitle: "Vintage Folk Artist"
  coverimage: "/images/robb-hagle-cover.jpg"

  # Social information
  social:
    instagram: "https://www.instagram.com/robbd7/"
    soundcloud: "https://soundcloud.com/robb-hagle"
    reverbnation: "https://www.reverbnation.com/musician/robbhagle"
    tiktok: "https://www.tiktok.com/@robbhagle.music"
    contact: "mailto:contact@robbhagle.com"

  # Artist information
  authors:
    robbhagle:
      name: "Robb Hagle"
      description: "Folk musician from Fort Collins, CO blending classic acoustic folk songs with modern reinterpretations."
      image: "/images/robb-hagle-profile.jpg"
      link: "/"

  # Navbar links
  navbar:
    music: "/album/"
    sync: "/sync/"
    shows: "/show/"

  fonts: "Lato:300,500,700"
  maps: "true"
---
